Author.create!([
  {author_name: "sri lakshmi battula", sex: "Female", country: "india"},
  {author_name: "ankit battula", sex: "Male", country: "india"},
  {author_name: "prabhakar battula", sex: "Male", country: "india"},
  {author_name: "anjali battula", sex: "Female", country: "india"},
  {author_name: "subba rao pasupuleti", sex: "Male", country: "US"},
  {author_name: "aruna pasupuleti", sex: "Female", country: "US"},
  {author_name: "eesha meghana pasupuleti", sex: "Female", country: "US"},
  {author_name: "shakespeare", sex: "Male", country: "UK"},
  {author_name: "william words worth", sex: "Male", country: "UK"},
  {author_name: "abdul kalam", sex: "Male", country: "india"},
  {author_name: "krishna shastry", sex: "Male", country: "INDIA"},
  {author_name: "kalidas", sex: "Male", country: "INDIA"}
])
Book.create!([
  {book_name: "astrology as it is mundane", author_id: 7, price: "8.99"},
  {book_name: "ruby on rails stack overflow", author_id: 7, price: "32.0"},
  {book_name: "vah chef vantalu", author_id: 2, price: "9.89"},
  {book_name: "manchi muggulu", author_id: 2, price: "11.0"},
  {book_name: "rubik's made easy", author_id: 3, price: "56.0"},
  {book_name: "riding duro", author_id: 3, price: "12.0"},
  {book_name: "hanna montanna fairy tales", author_id: nil, price: "11.0"},
  {book_name: "hava havayi", author_id: nil, price: "0.39"},
  {book_name: "geology and mines", author_id: 7, price: "8.89"},
  {book_name: "wings of fire", author_id: 16, price: "125.0"},
  {book_name: "romeo and juliet", author_id: 13, price: "45.0"},
  {book_name: "much ado about nothing", author_id: 13, price: "0.98"},
  {book_name: "macabeth", author_id: 13, price: "2.89"},
  {book_name: "othello", author_id: 13, price: "8.89"},
  {book_name: "the comedy of errors", author_id: 13, price: "1.99"},
  {book_name: "ankit's adventures in antarctica", author_id: 3, price: "25.0"},
  {book_name: "my presidential days", author_id: 16, price: "69.54"},
  {book_name: "let it go", author_id: 11, price: "56.87"},
  {book_name: "kinder joy", author_id: 11, price: "0.65"},
  {book_name: "ode to duty", author_id: 14, price: "11.0"},
  {book_name: "veyi padagalu", author_id: 19, price: "12.56"},
  {book_name: "adbutha deepam", author_id: 19, price: "56.0"},
  {book_name: "music as it is", author_id: 10, price: "16.85"},
  {book_name: "cooking an egg less cake", author_id: 10, price: "45.0"},
  {book_name: "rails architecture", author_id: 9, price: "122.99"},
  {book_name: "mac apps", author_id: 9, price: "89.85"},
  {book_name: "chartered secretary", author_id: 7, price: "12.55"},
  {book_name: "my house colouring in dark colour", author_id: 2, price: "29.89"},
  {book_name: "my childhood events", author_id: 14, price: "12.59"},
  {book_name: "one day", author_id: 8, price: "5.5"},
  {book_name: "history during moghul era", author_id: 3, price: "12.99"}
])
